### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by zugofn** [Jiajun-Xiang/SMA-Net#1]
Hi,Sir!
Great results on KAIST！
Where i can find your paper about this work？（or What time will the code can be available?）I want to study it.

Have a good day!😊

**Comment by Jiajun-Xiang** [comment]
Hi!
Thank you for your attention！
My paper is still in the stage of submission and it's not published.I will open the code if my paper is accepted.It may take a long time.&nbsp;
Have a good day!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jiajun-Xiang/SMA-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 中午11:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Jiajun-Xiang/SMA-Net] About the paper (#1)





 
Hi,Sir!
 Great results on KAIST！
 Where i can find your paper about this work？（or What time will the code can be available?）I want to study it.
 
Have a good day!😊

**Comment by zugofn** [comment]
> Hi! Thank you for your attention！ My paper is still in the stage of submission and it's not published.I will open the code if my paper is accepted.It may take a long time.&nbsp; Have a good day!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiajun-Xiang/SMA-Net" ***@***.***&gt;; 发送时间:&nbsp;2021年5月14日(星期五) 中午11:32 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Jiajun-Xiang/SMA-Net] About the paper (#1) Hi,Sir! Great results on KAIST！ Where i can find your paper about this work？（or What time will the code can be available?）I want to study it. Have a good day!😊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for your quick reply！
Wish your article successfully accepted as soon as possible！😊

**Comment by xuhaha6** [comment]
> Hi! Thank you for your attention！ My paper is still in the stage of submission and it's not published.I will open the code if my paper is accepted.It may take a long time.&nbsp; Have a good day!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiajun-Xiang/SMA-Net" ***@***.***&gt;; 发送时间:&nbsp;2021年5月14日(星期五) 中午11:32 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Jiajun-Xiang/SMA-Net] About the paper (#1) Hi,Sir! Great results on KAIST！ Where i can find your paper about this work？（or What time will the code can be available?）I want to study it. Have a good day!😊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Dear Dr. Xiang
 I am a 2rd-year undergraduate student, majoring in Control Science and Engineering, and I am doing research works about multispectral pedestrian detection, which is closely related to your published paper entitled “RGB-Thermal based Pedestrian Detection with Single-Modal Augmentation and ROI Pooling Multiscale Fusion” IGARSS2022.
 
  Your paper is very interesting and gives me great inspiration. Since I am now trying to reproduce your proposed SMA-Net and I'm afraid I cannot thoroughly understand the technical details in your paper. Meanwhile, I also refer to your paper to add a set of comparative experiments. Would you please share your source code with me for research purposes only? I assure you explicitly that the code will not be used for commercial purposes. And I promise your paper will be well-cited if I finally use the code. My mailbox：xzy568228346@163.com
   Your kind help will be highly appreciated.
